<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>XGecu T48 SDK CLI</Title>
    <Product>XGecu T48 SDK</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\T48Sdk\T48.SDK.csproj" SetTargetFramework="TargetFramework=net10.0-windows" />
  </ItemGroup>
</Project>
